= Step 3 : Create a new project

=== 3.1 Create a Vert.x Project
First things first create a new directory for your work.  If you are using Windows you should probably create a folder directly on the C drive to prevent any weirdness that could arise from path names.

From inside that directory run the following maven command :

```
mvn io.fabric8:vertx-maven-plugin:1.0.13:setup -DvertxVersion=3.5.1 
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- vertx-maven-plugin:1.0.13:setup (default-cli) @ standalone-pom ---
[INFO] No pom.xml found, creating it in /home/dphillips/Documents/RedHat/Workspace/rhoar-kubernetes-qcon-2018/insult-service
Set the project groupId [io.vertx.example]: com.redhat.qcon
Set the project artifactId [my-vertx-project]: insult-service
Set the project version [1.0-SNAPSHOT]: 1.0.0-SNAPSHOT
Set the vertcile class name [MainVerticle]:
[INFO] Creating verticle MainVerticle
[INFO] Creating directory /home/dphillips/Documents/RedHat/Workspace/rhoar-kubernetes-qcon-2018/insult-service/src/main/java/com/redhat/qcon
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 34.510 s
[INFO] Finished at: 2018-05-21T12:07:46-04:00
[INFO] Final Memory: 9M/166M
[INFO] ------------------------------------------------------------------------
```
This will create a new Maven POM file populated based on the values you entered during the setup.

=== 3.2 Update pom.xml
After the POM file has been created, we will need to add some additional libraries for this microservice:

* vertx-web-api-contract
* vertx-rx-java2
* vertx-service-proxy
* vertx-sockjs-service-proxy
* vertx-config-kubernetes-configmap
* vertx-codegen
* vertx-lang-js

To save time there is a complete pom.xml in this directory.  Copy and paste the pom.xml into your dirctory.  We will look at the specific additions as we use them in the tutorial.

link:pom.xml [Open the pom.xml]

=== 3.3 Add Your New Project To GitHub

```
$ git init
$ git add pom.xml src
$ git commit -am 'Initial import'
$ git push origin master
```